networks:
  npm_default:
    external: true

services:
  # Base de données MongoDB
  mongodb:
    image: mongo:latest
    container_name: emergent-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    networks:
      - npm_default

  # API Backend (FastAPI)
  backend:
    build: ./backend
    container_name: emergent-backend
    volumes:
      - resources-data:/app/storage
      - ./activity-video:/data/activity:ro
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - npm_default

  # Application Frontend (React)
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=https://api.loasis.app
    container_name: emergent-frontend
    depends_on:
      - backend
    networks:
      - npm_default

volumes:
  mongo-data:
  resources-data:
